### ISSUE TITLE
Aktualisiertes Klassendiagramm

### ISSUE THREAD

**Issue by althomi** [calvinrbnspiess/mooscraft#1]
- händisch erstellen or autom. via IntelliJ

Frage: Was meinst du mit händisch?
Und können wir die Programme vielleicht jetzt bei GitHub und Java belassen? 
Ich denke ich spreche auch für Julia und Larissa, dass wir schon genügend nen dicken Kopf haben mit den beiden Sachen:)

**Comment by calvinrbnspiess** [comment]
<img width="886" alt="Bildschirmfoto 2019-10-24 um 10 48 27" src="https://user-images.githubusercontent.com/5459550/67469017-d3542d00-f64b-11e9-9307-472bea85ec0c.png">
