### ISSUE TITLE
Was passiert wenn kein Befehl erkannt wurde?

### ISSUE THREAD

**Issue by althomi** [calvinrbnspiess/mooscraft#2]
Es sollte eine UnknownAction mit kleiner Fehlermeldung und Verweis auf "help" eingeblendet werden

Frage: Was meinst du mit kein Befehl erkannt? In welchem Kontext?

**Comment by calvinrbnspiess** [comment]
Der Spieler gibt etwas ein, was nicht vorgesehen ist. Statt "weiter" zb "hallo" ...
So ein Fall wäre nicht vorgesehen und soll abgefangen werden
