### ISSUE TITLE
Grundzüge der Game-Engine implementieren

### ISSUE THREAD

**Issue by althomi** [calvinrbnspiess/mooscraft#4]
Wie sieht das denn aus? Was genau ist damit gemeint? Kannst du da was schicken?

**Comment by calvinrbnspiess** [comment]
Habe mal versucht das in Illustrator (mit schrecklicher Ausführung) zu veranschaulichen:


![mooscraft-struktur](https://user-images.githubusercontent.com/5459550/67527835-2f549b00-f6b8-11e9-99a9-19abe12e7258.png)
